spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.migrations-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/firm-system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  server:
    port: 8080
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
